### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by khansaad1275** [F33Z/instashell#14]
I placed my password in the password list so i can test it on my account and it just not detect my password, so i think its not working / it's just a prank tool. These tool usually work when you will place your password at line 19 or 20 but they will ignore your password even if it is correct at location 220 or something, basically anything over 20 i think. If anyone had any success with this please let me know.

**Comment by narkane** [comment]
yes i also had this issue. if anybody knows the reason. i guess if the program just fake or something thats fine. im more concerned that it found it and dumped it to the user who "cloned" the original thelinuxchoice repo. that they didnt upload a clone but a altered version that their using to have us phish accounts for them *sigh* what a nuisance.,
btw if u ever fixed it @khansaad1275 pls lmk 😁

**Comment by itmefeez** [comment]
This repository is an original fork, and no further changes will be made in this repo. However, you are welcome to fork it and make changes as per your needs.
