### ISSUE TITLE
an error while executing (./instashell.sh) command

### ISSUE THREAD

**Issue by Hamay-Jaza** [F33Z/instashell#2]
when I try to enter this command (./instashell.sh) this error shows.
root@Hama:~/bruteforce/instashell# ./instashell.sh
./instashell.sh: line 133: syntax error near unexpected token `('
./instashell.sh: line 133: `printf "\e[1;92mWordlist:\e[0m\e[1;77m %s (%s)\e[0m\n" $wl_pass $count_pass'

**Comment by itmefeez** [comment]
Sorry about that but I didn't develop this.

And the original developer removed their Github account.

I will try to fix this :)

[Fell free to DM on Instagram @itmefeez](https://instagram.com/itmefeez)

**Comment by Kaungc** [comment]
I request send nameyoyo555665
