### ISSUE TITLE
random command execution

### ISSUE THREAD

**Issue by ghost** [F33Z/instashell#5]
When running a custom wordlist, passwords which include periods, underscores and dashes have a tendancy to cause issues with the code that is running, which ends up with error messages for grep and passwords appearing where they shouldnt be. Here is an example:

```
Trying pass (3632/3634): 1939420
Trying pass (.trujillo10/): 
Trying pass (3621/1939420): 10trujillo_
Trying pass (3622/1939420): _trujillo10
Trying pass (3623/1939420): 10trujillo-
grep: invalid option -- 't'
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```

**Comment by itmefeez** [comment]
This doesn't affect any execution.

I will try to fix this

**Comment by sahil-dhuri** [comment]
> This doesn't affect any execution.
> 
> I will try to fix this

right password is present in list then also its not maching ..pls solve it
